# Generated by Django 3.0.2 on 2020-01-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACCESSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Utente', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=100)),
                ('Mail', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CLIENTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodiceFiscale', models.CharField(max_length=200)),
                ('Nome', models.CharField(max_length=200)),
                ('Cognome', models.CharField(max_length=200)),
                ('Telefono_casa', models.CharField(max_length=200, null=True)),
                ('Telefono_Cellulare', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Data_di_Nascita', models.DateTimeField()),
                ('Accesso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NEGOZIO.ACCESSO')),
            ],
        ),
        migrations.CreateModel(
            name='FORNITORE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LAVORATORE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200)),
                ('Cognome', models.CharField(max_length=200)),
                ('Matricola', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MERCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField(null=True)),
                ('Fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEGOZIO.FORNITORE')),
            ],
        ),
        migrations.CreateModel(
            name='PUNTO_VENDITA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200)),
                ('Indirizzo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VIDEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regista', models.CharField(max_length=200)),
                ('Autore', models.CharField(max_length=200)),
                ('CasaProdutrice', models.CharField(max_length=200)),
                ('Durata', models.DurationField()),
                ('Picture', models.URLField(null=True)),
                ('Genere', models.CharField(max_length=100)),
                ('Titolo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RESPONSABILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LAVORATORE_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEGOZIO.LAVORATORE')),
            ],
        ),
        migrations.CreateModel(
            name='OPERAZIONI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypoOperazione', models.BooleanField(default=True, null=True)),
                ('DataOperazione', models.DateTimeField(auto_now_add=True)),
                ('Merce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEGOZIO.MERCE')),
                ('PuntoVendita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEGOZIO.PUNTO_VENDITA')),
            ],
        ),
        migrations.CreateModel(
            name='NOLEGGIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataInizio', models.DateTimeField()),
                ('DataFine', models.DateTimeField(null=True)),
                ('Tariffe', models.IntegerField(null=True)),
                ('Quantita', models.IntegerField(null=True)),
                ('DataPrevista', models.DateTimeField(null=True)),
                ('Cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='NEGOZIO.CLIENTE')),
                ('PuntoVendita', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='NEGOZIO.PUNTO_VENDITA')),
            ],
        ),
        migrations.AddField(
            model_name='merce',
            name='Video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEGOZIO.VIDEO'),
        ),
        migrations.CreateModel(
            name='DOCUMENTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firma', models.URLField(null=True)),
                ('Cliente_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NEGOZIO.CLIENTE')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='Responsabile',
            field=models.ManyToManyField(blank=True, related_name='SCONTO', to='NEGOZIO.RESPONSABILE'),
        ),
        migrations.CreateModel(
            name='ADDETTI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lavorator_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEGOZIO.LAVORATORE')),
            ],
        ),
        migrations.AddField(
            model_name='accesso',
            name='Lavoratore_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NEGOZIO.LAVORATORE'),
        ),
    ]
