# Generated by Django 3.0.3 on 2020-02-23 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(db_column='Cliente_id', primary_key=True, serialize=False)),
                ('codicefiscale', models.CharField(blank=True, db_column='Codicefiscale', max_length=45, null=True)),
                ('data_di_nascita', models.CharField(blank=True, db_column='Data_di_nascita', max_length=45, null=True)),
                ('tipo', models.IntegerField(blank=True, db_column='Tipo', null=True)),
                ('last_update', models.DateTimeField(db_column='Last_update')),
                ('telefono_casa', models.CharField(blank=True, db_column='Telefono_casa', max_length=45, null=True)),
                ('telefono_cellulare', models.CharField(blank=True, db_column='Telefono_cellulare', max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('documento_id', models.AutoField(db_column='Documento_id', primary_key=True, serialize=False)),
                ('firma', models.IntegerField(db_column='Firma')),
            ],
        ),
        migrations.CreateModel(
            name='Lavoratore',
            fields=[
                ('lavoratore_id', models.AutoField(db_column='Lavoratore_id', primary_key=True, serialize=False)),
                ('matricola', models.CharField(blank=True, db_column='Matricola', max_length=45, null=True)),
                ('punto_vendita', models.ForeignKey(db_column='Punto_vendita_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.PuntoVendita')),
                ('responsabile', models.OneToOneField(blank=True, db_column='Responsabile_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.Lavoratore')),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestataNoleggio',
            fields=[
                ('testata_noleggio_id', models.AutoField(db_column='Testata_noleggio_id', primary_key=True, serialize=False)),
                ('prezzo_definitivo', models.CharField(db_column='Prezzo_definitivo', max_length=45)),
                ('data_fine', models.DateTimeField(db_column='Data_fine')),
                ('ricevuta_noleggio', models.IntegerField(db_column='Ricevuta_noleggio')),
                ('ricevuta_fine', models.IntegerField(db_column='Ricevuta_fine')),
                ('cliente', models.ForeignKey(db_column='Cliente_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.Cliente')),
                ('lavoratore', models.ForeignKey(db_column='Lavoratore_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.Lavoratore')),
            ],
        ),
        migrations.CreateModel(
            name='DetailNoleggio',
            fields=[
                ('noleggio_id', models.AutoField(db_column='Noleggio_id', primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField(db_column='Last_update')),
                ('dataprevista', models.DateTimeField(db_column='DataPrevista')),
                ('prezzo_effettivo', models.FloatField(db_column='Prezzo_effettivo')),
                ('sconto', models.FloatField(db_column='Sconto')),
                ('articolo', models.ForeignKey(db_column='Articolo_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.Articolo')),
                ('testata_noleggio', models.ForeignKey(db_column='Testata_noleggio_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.TestataNoleggio')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.ForeignKey(db_column='Documento_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.Documento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='utente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
