# Generated by Django 3.0.3 on 2020-02-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20200223_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listvideomerce',
            fields=[
                ('listvideomerce_id', models.IntegerField(blank=True, db_column='Listvideomerce_id', primary_key=True, serialize=False)),
                ('quantita_articolo', models.IntegerField()),
                ('negozio', models.CharField(max_length=45)),
                ('titolo', models.CharField(blank=True, db_column='Titolo', max_length=45, null=True)),
                ('autore', models.CharField(blank=True, db_column='Autore', max_length=200, null=True)),
                ('casaprodutrice', models.CharField(blank=True, db_column='CasaProdutrice', max_length=45, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=500, null=True)),
                ('durata', models.IntegerField(blank=True, db_column='Durata', null=True)),
                ('genere', models.CharField(blank=True, db_column='Genere', max_length=100, null=True)),
                ('regista', models.CharField(blank=True, db_column='Regista', max_length=100, null=True)),
                ('prezzo_listino', models.FloatField(db_column='Prezzo_listino')),
                ('cognome', models.CharField(blank=True, db_column='Cognome', max_length=45, null=True)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=45, null=True)),
                ('utente', models.CharField(db_column='Utente', max_length=45)),
            ],
        ),
    ]
